name: build and test
on:
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    name: build and test
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build All
        run: dotnet build
      - name: Test All
        run: dotnet test