name: Deploy Client to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - src/angular/**
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: src/angular
      run: npm install --legacy-peer-deps 

    - name: Build
      working-directory: src/angular
      run: npm run build:prod

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/client/dist/MovieMatch
        enable_jekyll: true
