name: Build and deploy to Azure
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "src/angular"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Connection String for Production
        uses: bariscanyilmaz/paste-secret@v1.1
        with:
          secrets: >
            [
              { "filename": "src/MovieMatch/MovieMatch.Web/appsettings.Production.json", "keys": [{"key": "CONNECTION_STRING","value": "${{secrets.CONNECTION_STRING}}"}]},
              { "filename": "src/MovieMatch/MovieMatch.DbMigrator/appsettings.Production.json", "keys": [{"key": "CONNECTION_STRING","value": "${{secrets.CONNECTION_STRING}}"}]}
            ]
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build src/MovieMatch.Web/MovieMatch.Web.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/MovieMatch.Web/MovieMatch.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "abpmoviematch"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A458D43365D54926AE2E70CFADECC7CA }}
          package: .
